# Generated by Django 3.2 on 2021-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maleteros', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio de los maleteros')),
                ('mantenimiento_areas', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio del mantenimiento de áreas comunes')),
                ('jardineria', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio de la jardineria')),
                ('mantenimiento_edificio', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio del mantenimiento del edificio')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Establecimiento de precio',
                'verbose_name_plural': 'Establecimiento de precios',
                'db_table': 'establecimiento_precios',
            },
        ),
    ]
