# Generated by Django 4.1.5 on 2023-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0002_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='factura',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='identificacion',
            field=models.CharField(default=12345, max_length=12, verbose_name='Número Identificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastos',
            name='metodo_pago',
            field=models.IntegerField(choices=[(0, 'EFECTIVO'), (1, 'PAGO MÓVIL'), (2, 'TRANSFERENCIA'), (3, 'DEPÓSITO')], null=True, verbose_name='Método Pago'),
        ),
    ]
