# Generated by Django 4.1.5 on 2023-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0003_gastos_factura_gastos_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='plataforma',
            field=models.TextField(default='Paypal', verbose_name='Plataforma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
