# Generated by Django 4.1.5 on 2023-11-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0004_movimientos_propietarios_plataforma_alter_tasas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='updated_at',
        ),
    ]
