# Generated by Django 4.1.5 on 2023-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0005_remove_movimientos_propietarios_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='abono',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Abono'),
        ),
    ]
