# Generated by Django 4.1.5 on 2023-11-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0006_movimientos_propietarios_abono'),
    ]

    operations = [
        migrations.RenameModel('Configuracion','Condominio'),
        migrations.AlterModelOptions(
            name='condominio',
            options={'verbose_name': 'Condominio', 'verbose_name_plural': 'Condominios'},
        ),
        migrations.RenameField(
            model_name='condominio',
            old_name='id_configuracion',
            new_name='id_condominio',
        ),
        migrations.AlterModelTable(
            name='condominio',
            table='condominio',
        ),
    ]
