# Generated by Django 4.1.5 on 2023-11-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0007_rename_configuracion_condominio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'verbose_name': 'Condominio', 'verbose_name_plural': 'Condominio'},
        ),
        migrations.AddField(
            model_name='bancos',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
