# Generated by Django 4.1.5 on 2023-11-29 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0008_alter_condominio_options_bancos_id_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
