# Generated by Django 4.1.5 on 2023-11-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0009_condominio_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
