# Generated by Django 4.1.5 on 2023-11-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0010_precios_id_condominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota_mensual',
            fields=[
                ('id_cuota_m', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de la publicacion de la cuota mensuald e condominio')),
                ('descripcion', models.TextField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=30)),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
            options={
                'verbose_name': 'Cuota_mensual',
                'verbose_name_plural': 'Cuotas_mensuales',
                'db_table': 'cuota_mensual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deudas_propietarios',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_deuda', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo_deuda', models.CharField(max_length=100)),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=30)),
                ('is_active', models.BooleanField(default=False, verbose_name='Esta activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'db_table': 'deudas',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CuentasxCobrar',
        ),
    ]
