# Generated by Django 4.1.5 on 2023-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0011_cuota_mensual_deudas_propietarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='estado_cuenta',
            field=models.CharField(max_length=30, null=True, verbose_name='Estado de cuenta'),
        ),
    ]
