# Generated by Django 4.1.5 on 2023-12-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0012_propietario_estado_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='estado_cuenta',
            new_name='estado_deuda',
        ),
    ]
