# Generated by Django 4.1.5 on 2023-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0013_rename_estado_cuenta_propietario_estado_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='abono',
        ),
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='tipo_pago',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de pago'),
        ),
    ]
