# Generated by Django 4.1.5 on 2023-12-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0014_remove_movimientos_propietarios_abono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='estado_deuda',
            field=models.BooleanField(default=False, verbose_name='Estado de cuenta'),
        ),
    ]
