# Generated by Django 4.1.5 on 2023-12-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0015_alter_propietario_estado_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota_mensual',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cuota_mensual',
            name='mes',
            field=models.TextField(default='Diciembre', verbose_name='Mes de pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuota_mensual',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de la publicacion de la cuota mensual de condominio'),
        ),
        migrations.CreateModel(
            name='Cuotas_extras',
            fields=[
                ('id_cuota_extra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de la publicacion de la cuota extra')),
                ('mes', models.TextField(verbose_name='Mes de la cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=30)),
                ('is_active', models.BooleanField(default=False, verbose_name='Esta activa?')),
                ('id_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.gastos')),
                ('id_propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario')),
            ],
        ),
    ]
