# Generated by Django 4.1.5 on 2023-12-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0016_remove_cuota_mensual_descripcion_cuota_mensual_mes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotas_extras',
            options={'managed': True, 'verbose_name': 'Cuota_extra', 'verbose_name_plural': 'Cuotas_extras'},
        ),
        migrations.AlterModelTable(
            name='cuotas_extras',
            table='cuotas_extras',
        ),
    ]
