# Generated by Django 4.1.5 on 2023-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0017_alter_cuotas_extras_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas_extras',
            name='is_all',
            field=models.BooleanField(default=False, verbose_name='Son todos?'),
        ),
    ]
