# Generated by Django 4.1.5 on 2023-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0018_cuotas_extras_is_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas_propietarios',
            name='is_moroso',
            field=models.BooleanField(default=False, verbose_name='Esta moroso?'),
        ),
    ]
