# Generated by Django 4.1.5 on 2023-12-12 19:17

import condominio_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0019_deudas_propietarios_is_moroso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_propietario',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_post', models.TextField(max_length=200)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=5000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=condominio_app.models.upload_location)),
                ('contacto', models.CharField(max_length=30, null=True, verbose_name='Número de teléfono')),
                ('horario_desde', models.TimeField(verbose_name='Horario para empezar a contactar')),
                ('horario_hasta', models.TimeField(verbose_name='Horario donde finaliza el contacto')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizado')),
                ('is_active', models.BooleanField(default=False, verbose_name='Esta activa?')),
                ('id_propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario')),
            ],
            options={
                'verbose_name': 'Post_propietario',
                'verbose_name_plural': 'Posts_propietarios',
                'db_table': 'post_propietario',
            },
        ),
    ]
