# Generated by Django 4.1.5 on 2023-12-13 17:50

import condominio_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0020_post_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='id_banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.bancos'),
        ),
        migrations.AlterField(
            model_name='post_propietario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models.upload_location_prop),
        ),
    ]
