# Generated by Django 4.1.5 on 2023-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0021_remove_movimientos_propietarios_plataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='estado_movimiento',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='movimientos_propietarios',
            name='referencia_movimiento',
            field=models.CharField(max_length=100, verbose_name='Referencia del movimiento'),
        ),
    ]
