# Generated by Django 4.1.5 on 2023-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0022_movimientos_propietarios_estado_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
