# Generated by Django 4.1.5 on 2023-12-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0023_movimientos_propietarios_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos_propietarios',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
