# Generated by Django 4.1.5 on 2023-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0024_rename_update_at_movimientos_propietarios_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_bancarios',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='movimientos_bancarios',
            name='saldo_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='saldo_anterior',
        ),
    ]
