# Generated by Django 4.1.5 on 2023-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0025_remove_movimientos_bancarios_saldo_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_bancarios',
            name='banco_emisor',
            field=models.CharField(max_length=255, null=True, verbose_name='Banco donde se realiza el pago'),
        ),
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='banco_emisor',
            field=models.CharField(max_length=255, null=True, verbose_name='Banco donde se realiza el pago'),
        ),
    ]
