# Generated by Django 4.1.5 on 2023-12-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0026_movimientos_bancarios_banco_emisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_recibo', models.TextField(verbose_name='Descripción del recibo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Monto recibo')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de realizacion')),
                ('hora_creacion', models.TimeField(verbose_name='Hora de realizacion')),
                ('id_movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibos',
            },
        ),
    ]
