# Generated by Django 4.1.5 on 2023-12-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0027_recibos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='id_recibo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.recibos'),
        ),
    ]
