# Generated by Django 4.1.5 on 2023-12-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0028_movimientos_propietarios_id_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='id_recibo',
        ),
    ]
