# Generated by Django 4.1.5 on 2023-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0029_remove_movimientos_propietarios_id_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_propietarios',
            name='referencia_movimiento',
            field=models.CharField(max_length=100, unique=True, verbose_name='Referencia del movimiento'),
        ),
    ]
