# Generated by Django 4.1.5 on 2023-12-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0030_alter_movimientos_propietarios_referencia_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_propietarios'),
        ),
    ]
