# Generated by Django 4.1.5 on 2023-12-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0031_alter_recibos_id_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='banco_emisor',
        ),
    ]
