# Generated by Django 4.1.5 on 2023-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0032_remove_movimientos_propietarios_banco_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_propietarios',
            name='banco_emisor',
            field=models.CharField(max_length=255, null=True, verbose_name='Banco donde se realiza el pago'),
        ),
    ]
