# Generated by Django 4.1.5 on 2023-12-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0033_movimientos_propietarios_banco_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas_extras',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='deudas_propietarios',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='post_propietario',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='recargos_y_descuentos',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
