# Generated by Django 4.1.5 on 2023-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0034_cuotas_extras_id_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='referencia_gasto',
            field=models.CharField(default='012', max_length=100, verbose_name='Referencia del gasto'),
            preserve_default=False,
        ),
    ]
