# Generated by Django 4.1.5 on 2023-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0035_gastos_referencia_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='referencia_gasto',
            field=models.CharField(max_length=100, verbose_name='Referencia del gasto'),
        ),
    ]
