# Generated by Django 4.1.5 on 2023-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0036_alter_gastos_referencia_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='forma_cobro',
            field=models.CharField(default='Condominio', max_length=12, verbose_name='Forma de cobro'),
            preserve_default=False,
        ),
    ]
