# Generated by Django 4.1.5 on 2023-12-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0037_gastos_forma_cobro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='mes',
        ),
    ]
