# Generated by Django 4.1.5 on 2023-12-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0039_movimientos_propietarios_id_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_propietarios',
            name='id_deuda',
        ),
        migrations.AddField(
            model_name='recibos',
            name='id_deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.deudas_propietarios'),
        ),
    ]
