# Generated by Django 4.1.5 on 2024-01-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0040_remove_movimientos_propietarios_id_deuda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='numero_aptos',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='saldo_edificio',
        ),
        migrations.CreateModel(
            name='Unidad_condominal',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del condominio')),
                ('saldo_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo actual en el condominio')),
                ('cantidad_domicilios', models.IntegerField(blank=True, null=True, verbose_name='Número de domicilios en el condominio')),
                ('identificacion_domicilio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de identificacion para cada domicilio')),
                ('pisos', models.IntegerField(blank=True, null=True, verbose_name='Número de pisos en el condominio')),
                ('tipo_unidad', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de unidad condominal')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
            options={
                'verbose_name': 'Unidad_condominal',
                'verbose_name_plural': 'Unidades_condominales',
                'db_table': 'unidad_condominal',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del condominio')),
                ('piso_domicilio', models.IntegerField(blank=True, null=True, verbose_name='Número de domicilios en el condominio')),
                ('tipo_hab', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de habitación')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.unidad_condominal')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
            },
        ),
    ]
