# Generated by Django 4.1.5 on 2024-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0041_remove_condominio_numero_aptos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad_condominal',
            name='identificacion_domicilio',
        ),
        migrations.AddField(
            model_name='unidad_condominal',
            name='cantidad_torres',
            field=models.IntegerField(null=True, verbose_name='Cantidad de torres de la unidad condominal'),
        ),
    ]
