# Generated by Django 4.2.8 on 2024-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0042_remove_unidad_condominal_identificacion_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_condominal',
            name='torres',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Torres'),
        ),
    ]
