# Generated by Django 4.2.8 on 2024-01-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0043_unidad_condominal_torres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad_condominal',
            name='torres',
        ),
    ]
