# Generated by Django 4.1.5 on 2024-01-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0044_remove_unidad_condominal_torres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='id_unidad',
        ),
        migrations.AddField(
            model_name='condominio',
            name='cantidad_domicilios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de domicilios en el condominio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='cantidad_torres',
            field=models.IntegerField(null=True, verbose_name='Cantidad de torres de la unidad condominal'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='pisos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de pisos en el condominio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='saldo_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo actual en el condominio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de unidad condominal'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.DeleteModel(
            name='Unidad_condominal',
        ),
    ]
