# Generated by Django 4.1.5 on 2024-01-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0045_remove_domicilio_id_unidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='saldo_unidad',
            new_name='saldo_condominio',
        ),
        migrations.RenameField(
            model_name='condominio',
            old_name='tipo_unidad',
            new_name='tipo_condominio',
        ),
    ]
