# Generated by Django 4.1.5 on 2024-01-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0046_rename_saldo_unidad_condominio_saldo_condominio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='saldo_condominio',
            new_name='saldo_edificio',
        ),
    ]
