# Generated by Django 4.1.5 on 2024-01-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0047_rename_saldo_condominio_condominio_saldo_edificio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='cantidad_domicilios',
            new_name='total_domicilios',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='id_condominio',
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id_torre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la torre')),
                ('cantidad_hab', models.IntegerField(blank=True, null=True, verbose_name='Número de domicilios en la torre')),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'db_table': 'torre',
            },
        ),
        migrations.CreateModel(
            name='DeudasCondominio',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('concepto_deuda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del condominio')),
                ('monto_deuda', models.IntegerField(blank=True, null=True, verbose_name='Número de domicilios en el condominio')),
                ('fecha_deuda', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de habitación')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.torre')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_torre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.torre'),
        ),
    ]
