# Generated by Django 4.1.5 on 2024-01-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0048_rename_cantidad_domicilios_condominio_total_domicilios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudascondominio',
            options={'verbose_name': 'Deuda del condominio', 'verbose_name_plural': 'Deudas del condominio'},
        ),
        migrations.AlterModelTable(
            name='deudascondominio',
            table='deuda_condominio',
        ),
    ]
