# Generated by Django 4.1.5 on 2024-01-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0049_alter_deudascondominio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudascondominio',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AlterField(
            model_name='deudascondominio',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Esta activa?'),
        ),
    ]
