# Generated by Django 4.1.5 on 2024-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0050_deudascondominio_id_condominio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudascondominio',
            name='monto_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Número de domicilios en el condominio'),
        ),
    ]
