# Generated by Django 4.1.5 on 2024-01-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0051_alter_deudascondominio_monto_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudascondominio',
            name='descripcion_deuda',
            field=models.TextField(default='Prueba', max_length=5000),
            preserve_default=False,
        ),
    ]
