# Generated by Django 4.1.5 on 2024-01-10 15:25

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0052_deudascondominio_descripcion_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models.img_gastos),
        ),
    ]
