# Generated by Django 4.2.8 on 2024-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0053_gastos_imagen_referencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='saldo_apertura',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=30, verbose_name='Saldo actual en el banco'),
            preserve_default=False,
        ),
    ]
