# Generated by Django 4.2.8 on 2024-01-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0054_bancos_saldo_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='saldo_apertura',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo actual en el banco'),
        ),
    ]
