# Generated by Django 4.2.8 on 2024-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0055_alter_bancos_saldo_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='nro_cuenta',
            field=models.CharField(max_length=35, null=True, verbose_name='Número de cuenta bancaria'),
        ),
    ]
