# Generated by Django 4.2.8 on 2024-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0056_alter_bancos_nro_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='saldo',
            new_name='saldo_bs',
        ),
        migrations.AddField(
            model_name='propietario',
            name='saldo_eur',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo del propietario'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='saldo_usd',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo del propietario'),
        ),
    ]
