# Generated by Django 4.2.8 on 2024-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0057_rename_saldo_propietario_saldo_bs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='saldo_bs',
            new_name='saldo',
        ),
    ]
