# Generated by Django 4.2.8 on 2024-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0058_rename_saldo_bs_propietario_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torre',
            name='cantidad_hab',
        ),
        migrations.AddField(
            model_name='condominio',
            name='saldo_edificio_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo actual en el condominio (EUR)'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='saldo_edificio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo actual en el condominio (USD)'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='estacionamientos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de estacionamientos por habitacion'),
        ),
        migrations.AddField(
            model_name='torre',
            name='pisos',
            field=models.IntegerField(blank=True, default=2, verbose_name='Cantidad de pisos de la torre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torre',
            name='nombre_torre',
            field=models.CharField(blank=True, default='Prueba', max_length=255, verbose_name='Nombre de la torre'),
            preserve_default=False,
        ),
    ]
