# Generated by Django 4.2.8 on 2024-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0059_remove_torre_cantidad_hab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='estacionamientos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de estacionamientos por domicilio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='nombre_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del domicilio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso_domicilio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piso del domicilio'),
        ),
    ]
