# Generated by Django 4.2.8 on 2024-01-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0060_alter_domicilio_estacionamientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='total_domicilios',
        ),
    ]
