# Generated by Django 4.2.8 on 2024-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0061_remove_condominio_total_domicilios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='tipo_ingreso',
            field=models.CharField(default='NOTA DE CRÉDITO', max_length=255, verbose_name='Tipo de ingreso'),
            preserve_default=False,
        ),
    ]
