# Generated by Django 4.2.8 on 2024-01-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0062_ingresos_tipo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondos',
            fields=[
                ('id_fondo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fondo', models.DateField(verbose_name='Fecha del fondo realizado')),
                ('tipo_fondo', models.CharField(max_length=255, verbose_name='Tipo de fondo')),
                ('concepto_fondo', models.CharField(max_length=255, verbose_name='Concepto del fondo')),
                ('monto_fondo', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Monto del fondo')),
                ('id_banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.bancos')),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
        ),
    ]
