# Generated by Django 4.2.8 on 2024-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0063_fondos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fondos',
            options={'managed': True, 'verbose_name': 'Fondo', 'verbose_name_plural': 'Fondos'},
        ),
        migrations.AlterModelTable(
            name='fondos',
            table='fondos',
        ),
    ]
