# Generated by Django 4.2.8 on 2024-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0064_alter_fondos_options_alter_fondos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='tipo_banco',
            field=models.CharField(default='Común', max_length=100, verbose_name='Tipo de banco'),
            preserve_default=False,
        ),
    ]
