# Generated by Django 4.2.8 on 2024-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0065_bancos_tipo_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='tipo_banco',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de banco'),
        ),
    ]
