# Generated by Django 4.2.8 on 2024-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0066_alter_bancos_tipo_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondos',
            name='tipo_movimiento',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de movimiento'),
        ),
    ]
