# Generated by Django 4.2.8 on 2024-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0067_fondos_tipo_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='tipo_ingreso',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de ingreso'),
        ),
    ]
