# Generated by Django 4.2.8 on 2024-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0068_alter_ingresos_tipo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='fecha_apertura',
            field=models.DateField(null=True, verbose_name='Fecha de apertura del banco'),
        ),
    ]
