# Generated by Django 4.2.8 on 2024-01-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0069_bancos_fecha_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondos',
            name='referencia_fondo',
            field=models.CharField(default=123, max_length=100, unique=True, verbose_name='Referencia del movimiento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cierre_mes',
            fields=[
                ('id_cierre', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cierre', models.DateField(null=True, verbose_name='Fecha de la publicacion de la cuota mensual de condominio')),
                ('pdf_cierre', models.FileField(null=True, upload_to='cierres/')),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
        ),
    ]
