# Generated by Django 4.2.8 on 2024-01-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0070_fondos_referencia_fondo_cierre_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierre_mes',
            options={'managed': True, 'verbose_name': 'Cierre_mes', 'verbose_name_plural': 'Cierres_mes'},
        ),
        migrations.AlterModelTable(
            name='cierre_mes',
            table='cierre_mes',
        ),
    ]
