# Generated by Django 4.2.8 on 2024-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0071_alter_cierre_mes_options_alter_cierre_mes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_mes',
            name='pdf_cierre',
            field=models.CharField(max_length=255, null=True, verbose_name='Concepto del fondo'),
        ),
    ]
