# Generated by Django 4.2.8 on 2024-02-06 19:03

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0072_alter_cierre_mes_pdf_cierre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudas_propietarios',
            options={'managed': True, 'verbose_name': 'Deuda_propietario', 'verbose_name_plural': 'Deudas_propietarios'},
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='pdf_cierre',
            field=models.FileField(null=True, upload_to=condominio_app.models.upload_cierres),
        ),
        migrations.AlterModelTable(
            name='deudas_propietarios',
            table='deudas_propietarios',
        ),
    ]
