# Generated by Django 4.2.8 on 2024-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0073_alter_deudas_propietarios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas_propietarios',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='deudas_propietarios',
            name='concepto_deuda',
            field=models.TextField(default='prueba', max_length=255, verbose_name='Descripcion del ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deudas_propietarios',
            name='descripcion_deuda',
            field=models.TextField(default='Prueba', verbose_name='Descripcion del ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deudas_propietarios',
            name='fecha_deuda',
            field=models.DateField(verbose_name='Fecha de la deuda'),
        ),
    ]
