# Generated by Django 4.2.8 on 2024-02-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0074_remove_deudas_propietarios_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='cantidad_torres',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='pisos',
        ),
        migrations.RemoveField(
            model_name='deudas_propietarios',
            name='id_condominio',
        ),
    ]
