# Generated by Django 4.2.8 on 2024-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0075_remove_condominio_cantidad_torres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='tipo_hab',
            new_name='tipo_domicilio',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='alicuota_apto',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='apto',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='size_apto',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='tipo_apto',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='alicuota_apto',
            field=models.FloatField(null=True, verbose_name='Alicuota del apartamento'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='size_domicilio',
            field=models.CharField(max_length=30, null=True, verbose_name='Tamaño de apartamento (m²)'),
        ),
    ]
