# Generated by Django 4.2.8 on 2024-02-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0076_rename_tipo_hab_domicilio_tipo_domicilio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='alicuota_apto',
            new_name='alicuota_domicilio',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_propietario',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario'),
            preserve_default=False,
        ),
    ]
