# Generated by Django 4.2.8 on 2024-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0077_rename_alicuota_apto_domicilio_alicuota_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Correo electrónico'),
        ),
    ]
