# Generated by Django 4.2.8 on 2024-02-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0078_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='id_condominio',
            new_name='condominio',
        ),
    ]
