# Generated by Django 4.2.8 on 2024-02-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0079_rename_id_condominio_propietario_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='condominio',
        ),
        migrations.AddField(
            model_name='propietario',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condominio', to='condominio_app.condominio'),
        ),
    ]
