# Generated by Django 4.2.8 on 2024-03-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0080_remove_propietario_condominio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas_propietarios',
            name='id_propietario',
        ),
        migrations.AddField(
            model_name='deudas_propietarios',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio'),
        ),
    ]
