# Generated by Django 4.2.8 on 2024-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0081_remove_deudas_propietarios_id_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas_propietarios',
            name='tipo_moneda',
            field=models.CharField(default='BS', max_length=100, verbose_name='Tipo de moneda en el cual se va a cobrar'),
            preserve_default=False,
        ),
    ]
