# Generated by Django 4.2.8 on 2024-03-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0083_deudascondominio_tipo_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='id_propietario',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio'),
        ),
    ]
