# Generated by Django 4.2.8 on 2024-03-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0084_remove_ingresos_id_propietario_ingresos_id_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='id_propietario',
        ),
        migrations.AddField(
            model_name='cuotas_extras',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio'),
        ),
    ]
