# Generated by Django 4.2.8 on 2024-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0085_remove_cuotas_extras_id_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='referencia_ingreso',
            field=models.CharField(default=123456, max_length=100, verbose_name='Referencia del movimiento'),
            preserve_default=False,
        ),
    ]
