# Generated by Django 4.2.8 on 2024-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0086_ingresos_referencia_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_mes',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
