# Generated by Django 4.2.8 on 2024-03-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0087_alter_cierre_mes_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fondos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
