# Generated by Django 4.2.8 on 2024-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0088_fondos_created_at_fondos_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='saldo_eur',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='saldo_usd',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo del propietario'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='saldo_eur',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo del propietario'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='saldo_usd',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Saldo del propietario'),
        ),
    ]
