# Generated by Django 4.2.8 on 2024-03-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0089_remove_propietario_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='condominio_app.condominio'),
            preserve_default=False,
        ),
    ]
