# Generated by Django 4.2.8 on 2024-03-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0090_remove_condominio_id_usuario_usuario_id_condominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255, verbose_name='Categoria del gasto')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
