# Generated by Django 4.2.8 on 2024-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0091_categoria_alter_usuario_id_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
