# Generated by Django 4.2.8 on 2024-03-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0092_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.categoria'),
            preserve_default=False,
        ),
    ]
