# Generated by Django 4.2.8 on 2024-03-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0093_gastos_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='codigo_tlf_1',
            field=models.CharField(default=58, max_length=15, verbose_name='Codigo de área 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='direccion_condominio',
            field=models.CharField(default='COSTA VERDE', max_length=255, verbose_name='Direccion del condominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='email',
            field=models.EmailField(default='gustavordgz15@gmail.com', max_length=100, verbose_name='Correo electrónico del condominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nombre_condominio',
            field=models.CharField(default='APART HOTEL ESPARTA SUITES', max_length=255, verbose_name='Nombre del condominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='rif_condominio',
            field=models.CharField(default='J-30456994-7', max_length=255, verbose_name='RIF del condominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='saldo_edificio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Saldo actual en el condominio'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='saldo_edificio_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Saldo actual en el condominio (EUR)'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='saldo_edificio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Saldo actual en el condominio (USD)'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='tlf_1',
            field=models.CharField(default='02952671600', max_length=255, verbose_name='Telefono 1 del condominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
