# Generated by Django 4.2.8 on 2024-03-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0094_alter_condominio_codigo_tlf_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='id_torre',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.torre'),
            preserve_default=False,
        ),
    ]
