# Generated by Django 4.2.8 on 2024-03-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0095_alter_domicilio_id_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_torre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.torre'),
        ),
    ]
