# Generated by Django 4.2.8 on 2024-03-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0096_alter_domicilio_id_torre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudas',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('concepto_deuda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del condominio')),
                ('descripcion_deuda', models.TextField(max_length=5000)),
                ('monto_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Número de domicilios en el condominio')),
                ('fecha_deuda', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de habitación')),
                ('estado_deuda', models.BooleanField(default=False, verbose_name='Esta activa?')),
                ('tipo_moneda', models.CharField(max_length=100, verbose_name='Tipo de moneda en el cual se va a cobrar')),
                ('tipo_deuda', models.CharField(max_length=10)),
                ('is_moroso', models.BooleanField(default=False, verbose_name='Esta moroso?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'db_table': 'deudas',
            },
        ),
        migrations.RemoveField(
            model_name='deudas_propietarios',
            name='id_domicilio',
        ),
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='id_domicilio',
        ),
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='id_gasto',
        ),
        migrations.RemoveField(
            model_name='cuotas_extras',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='estado_deuda',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='id_condominio',
        ),
        migrations.DeleteModel(
            name='DeudasCondominio',
        ),
        migrations.AddField(
            model_name='cuotas_extras',
            name='id_deuda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.deudas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recibos',
            name='id_deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.deudas'),
        ),
        migrations.DeleteModel(
            name='Deudas_propietarios',
        ),
    ]
