# Generated by Django 4.2.8 on 2024-03-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0097_deudas_remove_deudas_propietarios_id_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
    ]
