# Generated by Django 4.2.8 on 2024-03-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0098_domicilio_id_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
            preserve_default=False,
        ),
    ]
