# Generated by Django 4.2.8 on 2024-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0099_alter_domicilio_id_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='tipo_deuda',
            field=models.CharField(max_length=15),
        ),
    ]
