# Generated by Django 4.2.8 on 2024-03-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0100_alter_deudas_tipo_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='estado_deuda',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='estado_deuda',
            field=models.BooleanField(default=False, verbose_name='Estado de cuenta en cuanto a deudas'),
        ),
    ]
