# Generated by Django 4.2.8 on 2024-03-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0101_rename_estado_deuda_deudas_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='id_condominio',
        ),
    ]
