# Generated by Django 4.2.8 on 2024-03-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0102_remove_domicilio_id_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Género del propietario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_dni',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte'), ('J', 'Jurídico'), ('G', 'Gubernamental'), ('R', 'RIF'), ('O', 'Otro')], default='V', max_length=1, verbose_name='Tipo de identificación'),
        ),
    ]
