# Generated by Django 4.2.8 on 2024-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0103_alter_propietario_genero_alter_propietario_tipo_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=2, verbose_name='Género del propietario'),
        ),
    ]
