# Generated by Django 4.2.8 on 2024-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0104_alter_propietario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo_dni',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte'), ('J', 'Jurídico'), ('G', 'Gubernamental'), ('R', 'RIF'), ('O', 'Otro')], default='V', max_length=2, verbose_name='Tipo de identificación'),
        ),
    ]
