# Generated by Django 4.2.8 on 2024-03-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0105_alter_propietario_tipo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='id_cuota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.cuotas_extras'),
        ),
        migrations.AlterField(
            model_name='deudas',
            name='monto_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Monto de la deuda'),
        ),
    ]
