# Generated by Django 4.2.8 on 2024-03-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0106_deudas_id_cuota_alter_deudas_monto_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='tipo_moneda',
        ),
    ]
