# Generated by Django 4.2.8 on 2024-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0107_remove_deudas_tipo_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='id_cuota',
        ),
        migrations.AddField(
            model_name='deudas',
            name='categoria_deuda',
            field=models.CharField(max_length=15, null=True, verbose_name='Categoria de la deuda ingresada'),
        ),
        migrations.DeleteModel(
            name='Cuotas_extras',
        ),
    ]
