# Generated by Django 4.2.8 on 2024-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0108_remove_deudas_id_cuota_deudas_categoria_deuda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_bancarios',
            name='fecha_movimiento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del movimiento bancario'),
        ),
        migrations.AlterField(
            model_name='movimientos_propietarios',
            name='fecha_movimiento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del movimiento'),
        ),
    ]
