# Generated by Django 4.2.8 on 2024-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0109_alter_movimientos_bancarios_fecha_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='tipo_deuda',
            field=models.IntegerField(choices=[('1', 'Condominio'), ('2', 'Propietario')], default='1', verbose_name='Entidad o domicilio deudor'),
        ),
    ]
