# Generated by Django 4.2.8 on 2024-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0110_alter_deudas_tipo_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='tipo_moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('BS', 'Bolívares')], default='BS', max_length=3, verbose_name='Tipo de moneda'),
        ),
    ]
