# Generated by Django 4.2.8 on 2024-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0111_deudas_tipo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='tipo_deuda',
            field=models.CharField(choices=[('1', 'Condominio'), ('2', 'Propietario')], default='1', verbose_name='Entidad o domicilio deudor'),
        ),
    ]
