# Generated by Django 4.2.8 on 2024-04-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0112_alter_deudas_tipo_deuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titular', models.CharField(max_length=20, verbose_name='Nombre del titular')),
                ('apellido_titular', models.CharField(max_length=20, verbose_name='Apellido del titular')),
                ('telefono_titular', models.CharField(max_length=20, verbose_name='Teléfono del titular')),
                ('correo_titular', models.CharField(max_length=30, verbose_name='Correo del titular')),
            ],
            options={
                'verbose_name': 'Datos_transaccion',
                'verbose_name_plural': 'Datos_transacciones',
                'db_table': 'datos_transaccion',
            },
        ),
        migrations.RemoveField(
            model_name='recibos',
            name='id_movimiento',
        ),
        migrations.AddField(
            model_name='movimientos_bancarios',
            name='estado_movimiento',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='movimientos_bancarios',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario'),
        ),
        migrations.DeleteModel(
            name='Movimientos_propietarios',
        ),
        migrations.AddField(
            model_name='datos_transaccion',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_bancarios'),
        ),
    ]
