# Generated by Django 4.2.8 on 2024-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0113_datos_transaccion_remove_recibos_id_movimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_transaccion',
            name='apellido_titular',
        ),
        migrations.AlterField(
            model_name='datos_transaccion',
            name='nombre_titular',
            field=models.CharField(max_length=30, verbose_name='Nombre del titular'),
        ),
    ]
