# Generated by Django 4.2.8 on 2024-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0114_remove_datos_transaccion_apellido_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_transaccion',
            name='tipo_transaccion',
            field=models.CharField(default='PAGO', max_length=10, verbose_name='tipo de Transacción'),
            preserve_default=False,
        ),
    ]
