# Generated by Django 4.2.8 on 2024-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0115_datos_transaccion_tipo_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_transaccion',
            name='codigo_area',
            field=models.CharField(default='+58', max_length=7, verbose_name='Codigo de área'),
            preserve_default=False,
        ),
    ]
