# Generated by Django 4.2.8 on 2024-04-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0116_datos_transaccion_codigo_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='categoria_recibo',
            field=models.CharField(default='SOLVENTE', max_length=20, verbose_name='Categoria del recibo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_bancarios'),
        ),
    ]
