# Generated by Django 4.2.8 on 2024-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0117_recibos_categoria_recibo_recibos_id_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='jardineria',
        ),
        migrations.RemoveField(
            model_name='precios',
            name='mantenimiento_areas',
        ),
        migrations.RemoveField(
            model_name='precios',
            name='mantenimiento_edificio',
        ),
        migrations.AddField(
            model_name='precios',
            name='otras_areas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio de otras áreas sociales'),
        ),
        migrations.AddField(
            model_name='precios',
            name='salon_fiesta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Precio del salón de fiesta'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='tipo_condominio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de unidad condominal'),
        ),
    ]
