# Generated by Django 4.2.8 on 2024-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0118_remove_precios_jardineria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='categoria_gasto',
            field=models.CharField(max_length=25, null=True, verbose_name='Categoría del gasto'),
        ),
    ]
