# Generated by Django 4.2.8 on 2024-04-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0119_gastos_categoria_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='categoria_gasto',
        ),
    ]
