# Generated by Django 4.2.8 on 2024-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0120_remove_gastos_categoria_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_transaccion',
            name='codigo_area',
            field=models.CharField(max_length=7, null=True, verbose_name='Codigo de área'),
        ),
        migrations.AlterField(
            model_name='datos_transaccion',
            name='correo_titular',
            field=models.CharField(max_length=30, null=True, verbose_name='Correo del titular'),
        ),
        migrations.AlterField(
            model_name='datos_transaccion',
            name='telefono_titular',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono del titular'),
        ),
    ]
