# Generated by Django 4.2.8 on 2024-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0121_alter_datos_transaccion_codigo_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_propietario',
            name='contacto',
            field=models.IntegerField(max_length=30, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='post_propietario',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post_propietario',
            name='tipo_post',
            field=models.TextField(max_length=25),
        ),
    ]
