# Generated by Django 4.2.8 on 2024-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0122_alter_post_propietario_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_propietario',
            name='categoria_post',
            field=models.TextField(default='PERMANENTE', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_propietario',
            name='cod_tlf',
            field=models.CharField(default='+58', max_length=50, verbose_name='Código de área habitación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_propietario',
            name='contacto',
            field=models.IntegerField(null=True, verbose_name='Número de teléfono'),
        ),
    ]
