# Generated by Django 4.2.8 on 2024-04-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0123_post_propietario_categoria_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_propietario',
            name='id_propietario',
        ),
        migrations.AddField(
            model_name='post_propietario',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio'),
        ),
        migrations.AlterField(
            model_name='post_propietario',
            name='categoria_post',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
