# Generated by Django 4.2.8 on 2024-04-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0124_remove_post_propietario_id_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_propietario',
            name='contacto',
            field=models.CharField(max_length=255, null=True, verbose_name='Número teléfonico'),
        ),
    ]
