# Generated by Django 4.2.8 on 2024-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0125_alter_post_propietario_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_propietario',
            name='contacto',
            field=models.CharField(max_length=20, null=True, verbose_name='Número teléfonico'),
        ),
    ]
