# Generated by Django 4.2.8 on 2024-04-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0126_alter_post_propietario_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='id_domicilio',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='is_service',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.propietario'),
        ),
        migrations.AddField(
            model_name='movimientos_bancarios',
            name='tipo_moneda',
            field=models.CharField(max_length=10, null=True, verbose_name='Moneda del pago'),
        ),
    ]
