# Generated by Django 4.2.8 on 2024-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0127_remove_ingresos_id_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_bancarios',
            name='estado_movimiento',
            field=models.IntegerField(null=True, verbose_name='Estado del pago'),
        ),
    ]
