# Generated by Django 4.2.8 on 2024-04-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0128_alter_movimientos_bancarios_estado_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_propietario',
        ),
        migrations.AddField(
            model_name='propietario',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.propietario'),
        ),
    ]
