# Generated by Django 4.2.8 on 2024-05-28 14:57

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0129_remove_usuario_id_propietario_propietario_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('G', 'Gerente'), ('P', 'Portero')], default='A', max_length=2, verbose_name='Tipo de rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='ingresos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models.img_ingresos),
        ),
        migrations.AlterField(
            model_name='deudas',
            name='tipo_moneda',
            field=models.CharField(choices=[('BS', 'Bolívares'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='BS', max_length=3, verbose_name='Tipo de moneda'),
        ),
        migrations.AlterField(
            model_name='movimientos_bancarios',
            name='referencia_movimiento',
            field=models.CharField(max_length=100, null=True, verbose_name='Referencia del movimiento bancario'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='nombre_torre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la torre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='pisos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de pisos de la torre'),
        ),
    ]
