# Generated by Django 4.2.8 on 2024-05-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0130_rol_ingresos_imagen_referencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actas',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=255, verbose_name='Nombre del condominio')),
                ('imagen_referencial', models.CharField(max_length=255, verbose_name='RIF del condominio')),
                ('id_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'db_table': 'actas',
            },
        ),
    ]
