# Generated by Django 4.2.8 on 2024-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0131_actas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Pres', 'Presidente'), ('Secr', 'Secretario/a'), ('Miem', 'Miembros'), ('Por', 'Portero')], default='Admin', max_length=10, verbose_name='Tipo de rol'),
        ),
    ]
