# Generated by Django 4.2.8 on 2024-07-01 18:30

import condominio_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0134_alter_noticia_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_post', models.TextField(choices=[('0', 'Alquiler'), ('1', 'Venta')], default='0', max_length=25, null=True)),
                ('categoria_post', models.TextField(choices=[('0', 'Residencial'), ('1', 'Vacacional')], default='0', max_length=25, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=5000, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=condominio_app.models.upload_location_prop)),
                ('cod_tlf', models.CharField(max_length=50, verbose_name='Código de área habitación')),
                ('contacto', models.CharField(max_length=20, null=True, verbose_name='Número teléfonico')),
                ('horario_desde', models.TimeField(verbose_name='Horario para empezar a contactar')),
                ('horario_hasta', models.TimeField(verbose_name='Horario donde finaliza el contacto')),
                ('is_active', models.BooleanField(default=False, verbose_name='Esta activa?')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'db_table': 'alquiler',
            },
        ),
        migrations.AlterModelOptions(
            name='movimientos_bancarios',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='concepto_fondo',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='fecha_fondo',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='id_banco',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='monto_fondo',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='referencia_fondo',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='tipo_movimiento',
        ),
        migrations.RemoveField(
            model_name='fondos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='concepto_gasto',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='descripcion_gasto',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='fecha_gasto',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='id_banco',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='monto_gasto',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='referencia_gasto',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='concepto_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='descripcion_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='id_banco',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='id_propietario',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='monto_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='referencia_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='movimientos_bancarios',
            name='id_propietario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.condominio'),
        ),
        migrations.AddField(
            model_name='fondos',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_bancarios'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_bancarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='id_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.movimientos_bancarios'),
        ),
        migrations.AddField(
            model_name='movimientos_bancarios',
            name='concepto_movimiento',
            field=models.CharField(default='xd', max_length=255, verbose_name='Concepto del ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.rol'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='metodo_pago',
            field=models.IntegerField(choices=[('0', 'Efectivo'), ('1', 'Pago Móvil'), ('2', 'Transferencia'), ('3', 'Depósito')], null=True, verbose_name='Método Pago'),
        ),
        migrations.AlterModelTable(
            name='movimientos_bancarios',
            table='movimientos',
        ),
        migrations.DeleteModel(
            name='Post_propietario',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.domicilio'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='id_noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio_app.noticia'),
        ),
    ]
