# Generated by Django 4.2.8 on 2024-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0135_alquiler_alter_movimientos_bancarios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'Presidente'), ('2', 'Secretario/a'), ('3', 'Miembros'), ('4', 'Portero')], default='0', max_length=10, verbose_name='Tipo de rol'),
        ),
    ]
