# Generated by Django 4.2.8 on 2024-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0136_alter_rol_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'Presidente'), ('2', 'Secretario/a'), ('3', 'Junta'), ('4', 'Propietario'), ('5', 'Portero')], default='0', max_length=10, verbose_name='Tipo de rol'),
        ),
    ]
