# Generated by Django 4.2.8 on 2024-07-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0138_alter_rol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.condominio'),
        ),
    ]
