# Generated by Django 4.2.8 on 2024-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0139_usuario_id_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_transaccion',
            name='dni_titular',
            field=models.CharField(max_length=20, null=True, verbose_name='Identificación'),
        ),
    ]
