# Generated by Django 4.2.8 on 2024-07-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0140_datos_transaccion_dni_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.propietario'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
