# Generated by Django 4.2.8 on 2024-07-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0142_ingresos_factura_ingresos_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondos',
            name='factura',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='fondos',
            name='metodo_pago',
            field=models.IntegerField(choices=[('0', 'Efectivo'), ('1', 'Pago Móvil'), ('2', 'Transferencia'), ('3', 'Depósito')], null=True, verbose_name='Método Pago'),
        ),
    ]
