# Generated by Django 4.2.8 on 2024-07-04 04:21

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0143_fondos_factura_fondos_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models.img_fondos),
        ),
    ]
