# Generated by Django 4.2.8 on 2024-07-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0144_fondos_imagen_referencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prop_dom', to='condominio_app.propietario'),
        ),
    ]
