# Generated by Django 4.2.8 on 2024-07-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0145_alter_domicilio_id_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(max_length=8, null=True, verbose_name='cedula del cliente')),
                ('telefono', models.IntegerField(max_length=11, null=True, verbose_name='Telefono del cliente')),
                ('Banco', models.CharField(max_length=20, null=True, verbose_name='Banco del cliente')),
                ('referenncia_bancaria', models.IntegerField(max_length=15, null=True, verbose_name='Referencia bancaria')),
                ('Fecha_entrada', models.DateField(null=True, verbose_name='Fecha de entrada')),
                ('Fecha_salida', models.DateField(null=True, verbose_name='Fecha de salida')),
                ('id_alquiler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='condominio_app.alquiler')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'Reservacion',
            },
        ),
    ]
