# Generated by Django 4.2.8 on 2024-08-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0146_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='apellido',
            field=models.CharField(null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.BooleanField(default=False, null=True, verbose_name='estado de reserva'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='nombre',
            field=models.CharField(null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='soporte_pago',
            field=models.ImageField(null=True, upload_to='', verbose_name='Soporte de pago'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cedula',
            field=models.IntegerField(null=True, verbose_name='cedula del cliente'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='referenncia_bancaria',
            field=models.IntegerField(null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(null=True, verbose_name='Telefono del cliente'),
        ),
    ]
