# Generated by Django 4.2.8 on 2024-08-22 13:13

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0147_reservacion_apellido_reservacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservacies'},
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cedula',
            field=models.CharField(null=True, verbose_name='cedula del cliente'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='referenncia_bancaria',
            field=models.CharField(null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='soporte_pago',
            field=models.ImageField(null=True, upload_to=condominio_app.models.Reservacion.img_reservacion),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(null=True, verbose_name='Telefono del cliente'),
        ),
    ]
