# Generated by Django 4.2.8 on 2024-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0148_alter_reservacion_options_alter_reservacion_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.TextField(choices=[('0', 'Reservado'), ('1', 'Disponible')], default='1', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cedula',
            field=models.IntegerField(null=True, verbose_name='cedula del cliente'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='referenncia_bancaria',
            field=models.IntegerField(null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(null=True, verbose_name='Telefono del cliente'),
        ),
    ]
