# Generated by Django 4.2.8 on 2024-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0149_alquiler_estado_alter_reservacion_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='cedula',
            field=models.CharField(null=True, verbose_name='cedula del cliente'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='referenncia_bancaria',
            field=models.CharField(null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(null=True, verbose_name='Telefono del cliente'),
        ),
    ]
