# Generated by Django 4.2.8 on 2024-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0150_alter_reservacion_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.BooleanField(default=False, null=True, verbose_name='Disponibilidad el alquiler'),
        ),
    ]
