# Generated by Django 4.2.8 on 2026-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0151_alter_alquiler_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.BooleanField(default=False, null=True, verbose_name='Disponibilidad el inmueble'),
        ),
    ]
