# Generated by Django 4.2.8 on 2026-01-31 03:06

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0152_alter_alquiler_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models.Bancos.img_bancos),
        ),
    ]
