# Generated by Django 4.2.8 on 2026-02-03 21:31

import condominio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0153_bancos_imagen_referencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.upload_location_prop),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.Bancos.img_bancos),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='pdf_cierre',
            field=models.FileField(max_length=255, null=True, upload_to=condominio_app.models.upload_cierres),
        ),
        migrations.AlterField(
            model_name='fondos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.img_fondos),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.img_gastos),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='imagen_referencial',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.img_ingresos),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=condominio_app.models.upload_location),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='soporte_pago',
            field=models.ImageField(max_length=255, null=True, upload_to=condominio_app.models.Reservacion.img_reservacion),
        ),
    ]
