# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0154_alter_alquiler_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='superficie_total_m2',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Opcional. Si se define, las alícuotas se calculan como (m² del inmueble / este total).',
                max_digits=12,
                null=True,
                verbose_name='Superficie total del edificio (m²)'
            ),
        ),
    ]
