# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0155_condominio_superficie_total_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_transaccion',
            name='nombre_banco',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Nombre del banco (emisor)'
            ),
        ),
    ]
