# Generated by Django 4.2.8

from django.db import migrations, models
import condominio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0156_datos_transaccion_nombre_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='banner_1',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models._banner_upload_to, verbose_name='Banner 1 inicio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models._banner_upload_to, verbose_name='Banner 2 inicio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to=condominio_app.models._banner_upload_to, verbose_name='Banner 3 inicio'),
        ),
    ]
