# Generated by Django 4.2.8 on 2026-03-15 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0157_condominio_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='porcentaje_fondo_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de los gastos del período que se aparta para el fondo de reserva (1-100). Debe estar definido para realizar el cierre.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje del fondo de reserva'),
        ),
    ]
