# Generated by Django 4.2.8 on 2026-03-15 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0158_condominio_porcentaje_fondo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre_mes',
            name='porcentaje_fondo_reserva_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje fondo reserva usado en este cierre'),
        ),
    ]
