# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_app', '0159_cierre_mes_porcentaje_fondo_reserva_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico del condominio'),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='email_titular',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico del titular'),
        ),
        migrations.AlterField(
            model_name='datos_transaccion',
            name='correo_titular',
            field=models.CharField(max_length=254, null=True, verbose_name='Correo del titular'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='dni',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de identificación'),
        ),
    ]
