"""
Django settings for condominio project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os
import django_heroku
import sys

# Prefijo porque la app vive bajo /condominio
FORCE_SCRIPT_NAME = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')

# Archivos estáticos
#STATIC_URL = f'{FORCE_SCRIPT_NAME}/static/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Archivos subidos por usuarios
#MEDIA_URL = f'{FORCE_SCRIPT_NAME}/media/'
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR
print("STATIC_URL:", STATIC_URL, file=sys.stderr)
print("MEDIA_URL:", MEDIA_URL, file=sys.stderr)
#CONFIGURACION ANTERIOR
#STATIC_DIR = os.path.join(BASE_DIR, 'static')
#MEDIA_DIR = os.path.join(BASE_DIR, 'media')
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8hmlhm#9$gflacs96fqlu66!*y&mhn3nh(861^v=jwn3+z&ui9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#For Email
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
    'django.core.serializers',
    'django.contrib.humanize',

    # APP
    'condominio_app',

    # ADDONS
    'widget_tweaks',
    'mathfilters',
    'whitenoise',
    'crispy_forms',
    "crispy_bootstrap5",


]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'condominio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'condominio_app.Usuario'

WSGI_APPLICATION = 'condominio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Local

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'saphiro-condominio',    
        'USER': 'postgres',
        'PASSWORD': 'C1234567c',        
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


#bd servidor vps (comentada - usar solo para migrar datos)
#DATABASES = {
#      'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'condo_db',
#        'USER': 'saphiro_user',
#        'HOST': '159.203.165.120',
#        'PORT': '5432',
#        'PASSWORD': 'C1234567c'
#    }
#}
#
#Heroku Database

# DATABASES = {
#       'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd9j59eb6u999qh',
#         'USER': 'dopsjzraynrxza',
#         'HOST': 'ec2-54-147-155-94.compute-1.amazonaws.com',
#         'PORT': '5432',
#         'PASSWORD': 'bc75998ac22eb7169d798d50c1f0741de3913cfdfe3558bead3f5e15afc8a7dc'
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 9}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
#esto sse puede eliminar de acá, después de probar que todo funcione
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#STATIC_URL = '/static/'
#MEDIA_URL = '/media/'
# Estáticos y media con el prefijo


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Datos para enviar un email a tráves de gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True  
EMAIL_USE_SSL = False  
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587  
EMAIL_HOST_USER = 'no.reply.arcadestation@gmail.com'
EMAIL_HOST_PASSWORD = 'rzxsqvjqwkwpjmwk'  

LOGIN_URL = '/'

REDIS_URL = os.getenv('rediss://:p3198b504c91a516c01b9efc31c7982fbb8acdfa3f1a22d6deb23b25876351e94@ec2-107-23-187-32.compute-1.amazonaws.com:10970')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'd9pfeic3solo7p'

django_heroku.settings(locals())